# Generated by Django 5.1.6 on 2025-03-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0003_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('LT', 'Lietuva'), ('LV', 'Latvija'), ('ES', 'Estija')], default='Lietuva', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
