# Generated by Django 5.1.6 on 2025-03-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0004_alter_city_country_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('Lietuva', 'Lietuva'), ('Latvija', 'Latvija'), ('Estija', 'Estija')], default='Lietuva', max_length=100),
        ),
    ]
